# Generated by Django 3.2.15 on 2025-12-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0016_auto_20251104_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoralicitacion',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='licitacion',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='operador',
        ),
        migrations.DeleteModel(
            name='Operador',
        ),
    ]
