# Generated by Django 3.2.15 on 2025-12-18 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0017_auto_20251217_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación / Creación'),
        ),
    ]
