# Generated by Django 3.2.15 on 2025-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0018_alter_licitacion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='profesional_a_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
