# Generated by Django 5.1.5 on 2025-12-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0019_licitacion_profesional_a_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='justificacion_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Justificación Plan Anual'),
        ),
    ]
