# Generated by Django 5.1.5 on 2025-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0020_licitacion_justificacion_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cierre_preguntas', 'Cierre Preguntas Portal'), ('respuestas_portal', 'Respuestas Portal'), ('cierre_ofertas', 'Cierre Ofertas Portal'), ('est_adjudicacion', 'Est. Adjudicación'), ('firma_contrato', 'Tope Firma Contrato'), ('general', 'General'), ('observacion', 'Nueva Observación')], default='general', max_length=30),
        ),
    ]
