# Generated by Django 5.1.5 on 2025-12-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0021_remove_notificacion_usuario_alter_notificacion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('observacion', 'Nueva Observación'), ('etapa', 'Cambio de Etapa'), ('cerrada', 'Licitación Cerrada'), ('documento', 'Documento Subido'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
