# Generated by Django 5.1.5 on 2025-12-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0022_notificacion_usuario_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='orden_compra_adjudicacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de compra de adjudicación'),
        ),
    ]
